name: Build PlatformIO ESP-IDF CI

on:
  pull_request:
    branches:
      - main

jobs:
  build_pio_espidf:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: ${{ runner.os }}-pip-
    - name: Cache PlatformIO
      uses: actions/cache@v2
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
    - name: Set up Python
      uses: actions/setup-python@v2
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio
    - name: Run PlatformIO
      run: |
        pio run -c examples/espidf/platformio.ini \
            -d examples/espidf/basic_usage \
            -e espidf_esp32 -e espidf_esp32_c3
        pio run -c examples/espidf/platformio.ini \
            -d examples/espidf/basic_usage_callbacks \
            -e espidf_esp32 -e espidf_esp32_c3
