name: Build AVR CI

on:
  pull_request:
    branches:
      - main
      - development

jobs:
  build_avr:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup
      run: |
        git submodule update --init --recursive
        chmod +x examples/avr/basic_usage/tools/*
    - name: Install C/C++ Toolchain
      run: |
        sudo apt-get update
        sudo apt-get -y install binutils
        sudo apt-get -y install make
        sudo apt-get -y install gcc-avr
        sudo apt-get -y install avr-libc
        sudo apt-get -y install cflow
    - name: Build
      run: |
        PWD=`pwd`
        cd examples/avr/basic_usage/build
        make clean
        make build DEVICE=atmega328p F_CPU=16000000L
        cd $PWD
        cd examples/avr/basic_usage_callbacks/build
        make clean
        make build DEVICE=atmega328p F_CPU=16000000L
