name: Build Linux CI

on:
  pull_request:
    branches:
      - main

jobs:
  build_linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup
      run: |
        chmod +x examples/linux/basic_usage/tools/*
    - name: Install C/C++ Toolchain
      run: |
        sudo apt-get update
        sudo apt-get -y install binutils
        sudo apt-get -y install make
        sudo apt-get -y install gcc
        sudo apt-get -y install g++
        sudo apt-get -y install libc6
        sudo apt-get -y install cflow
    - name: Build
      run: |
        cd examples/linux/basic_usage/build
        make clean
        make build
